<?php

require_once dirname(__FILE__) . '/../../../system/Exceptions/LoginException.php';

/**
 * Test class for LoginException.
 * Generated by PHPUnit on 2012-01-07 at 17:52:00.
 */
class LoginExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LoginException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoginException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function test__toString() {
        $this->setExpectedException('LoginException');
        throw new LoginException();
    }

}

?>
