<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="pt-br" dir="ltr" xml:lang="pt-br" xmlns="http://www.w3.org/1999/xhtml">
	
    <head profile="http://gmpg.org/xfn/11">

            <!-- TITULO -->
            <title>
                    <?php   echo SYSTEMNAME." - ";
                            echo $controller;
                            echo $action ?>
            </title>
            <!-- /TITULO -->

            <!-- METAS -->
            <meta http-equiv="X-UA-Compatible" content="IE=8" />
            <meta http-equiv="Content-type"	content="text/html; charset=UTF-8" />
            <meta http-equiv="content-style-type" content="text/css" />
            <meta name="author" content="Renie Siqueira da Silva" />
            <!-- /METAS -->

            <!-- CSS -->
            <link media="screen" type="text/css" rel="stylesheet" href="<?php echo CSS ?>/general.css" />
            <link media="screen" type="text/css" rel="stylesheet" href="<?php echo CSS ?>/components.css" />
            <link media="screen" type="text/css" rel="stylesheet" href="<?php echo CSS.'/'.$controllerIdentification?>.css" />
            <!-- /CSS -->

            <!--  FAVICON -->
            <link rel="icon" href="<?php echo IMG ?>/favicon.ico" />
            <link rel="shortcut icon" href="<?php echo IMG ?>/favicon.ico" />
            <!--  /FAVICON -->

    </head>