<div class="menu">
    <ul>
        <li>Ordens
            <ul>
                <li><a href="<?php echo BASEURL?>ordens/criar" title="Ir para a página de cadastro de Ordens de Serviço">Cadastrar Ordens</a></li>
                <li><a href="<?php echo BASEURL?>ordens/buscar" title="Ir para a página de consulta de Ordens de Serviço">Buscar Ordens</a></li>
                <li><a href="<?php echo BASEURL?>ordens/buscarPorFuncionario" title="Ir para a página de busca de Ordens de Serviço por Funcionario">Buscar Ordens por Funcionário</a></li>
            </ul>
        </li>
        <li>Funcionários
            <ul>
                <li><a href="<?php echo BASEURL?>funcionarios/criar" title="Ir para a página de cadastro de Funcionários">Cadastrar Funcionários</a></li>
                <li><a href="<?php echo BASEURL?>funcionarios/buscar" title="Ir para a página de busca de Funcionários">Buscar Funcionários</a></li>
            </ul>
        </li>
        <li>Clientes
            <ul>
                <li><a href="<?php echo BASEURL?>clientes/criar" title="Ir para a página de cadastro de Clientes">Cadastrar Clientes</a></li>
                <li><a href="<?php echo BASEURL?>clientes/buscar" title="Ir para a página de busca de Clientes">Buscar Clientes</a></li>
            </ul>
        </li>
    </ul>
</div>