<?php include_once(VIEWS.'parts/header.phtml'); ?>
    <body id="testDatepage" class="test">
        <h1 class="msg roundCorner">Test Date, Time and DateTime</h1>
        <ul>
            <li>Test Date 1: <?php echo $view_pureDate1?> to <?php echo $view_formattedDate1?></li>
            <li>Test Date 2: <?php echo $view_pureDate2?> to <?php echo $view_formattedDate2?></li>
            <li>Test Date 3: <?php echo $view_pureDate3?> to <?php echo $view_formattedDate3?></li>
            <li>Test Date 4: <?php echo $view_pureDate4?> to <?php echo $view_formattedDate4?></li>
            <li>Test Time 1: <?php echo $view_pureTime1?> to <?php echo $view_formattedTime1?></li>
            <li>Test Time 2: <?php echo $view_pureTime2?> to <?php echo $view_formattedTime2?></li>
            <li>Test Time 3: <?php echo $view_pureTime3?> to <?php echo $view_formattedTime3?></li>
            <li>Test Time 4: <?php echo $view_pureTime4?> to <?php echo $view_formattedTime4?></li>
            <li>Test DateTime 1: <?php echo $view_pureDateTime1?> to <?php echo $view_formattedDateTime1?></li>
            <li>Test DateTime 2: <?php echo $view_pureDateTime2?> to <?php echo $view_formattedDateTime2?></li>
            <li>Test DateTime 3: <?php echo $view_pureDateTime3?> to <?php echo $view_formattedDateTime3?></li>
            <li>Test DateTime 4: <?php echo $view_pureDateTime4?> to <?php echo $view_formattedDateTime4?></li>
        </ul>
    </body>
</html>