<?php include_once(VIEWS.'parts/header.phtml'); ?>
    <body id="testEmailpage" class="test">
        <h1 class="msg roundCorner">Test Email</h1>
        <ul>
            <li>E-mail 1: <?php echo $view_mail1?"Valid":"Invalid"?></li>
            <li>E-mail 2: <?php echo $view_mail2?"Valid":"Invalid"?></li>
            <li>E-mail 3: <?php echo $view_mail3?"Valid":"Invalid"?></li>
            <li>E-mail 4: <?php echo $view_mail4?"Valid":"Invalid"?></li>
            <li>E-mail 5: <?php echo $view_mail5?"Valid":"Invalid"?></li>
        </ul>
    </body>
</html>